#
# Module manifest for module 'PdbSourceIndexing'
#
# Generated by: Miguel Barro
#
# Generated on: 28/06/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PdbSourceIndexing.psm1'

# Version number of this module.
ModuleVersion = '1.1.0'

# Supported PSEditions
CompatiblePSEditions = 'Desktop', 'Core'

# ID used to uniquely identify this module
GUID = 'b9a8c49c-0527-4928-949a-b5fea4b93cca'

# Author of this module
Author = 'Miguel Barro'

# Company or vendor of this module
CompanyName = 'Stan''s Previously Owned Repos'

# Copyright statement for this module
Copyright = '(c) 2025 Stan''s. All rights reserved'

# Description of the functionality provided by this module
Description = 'Source index PDB files to allow debuggers reference sources on github'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Update-PdbSourceIndexing'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
# CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'fixpdb'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'PdbSourceIndexing.psm1', 'cmdlets\Update-PdbSourceIndexing.ps1'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'C','C++','PDB','SourceIndexing','SRCSVR','Windows','Windbg','Cdb'

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/MiguelBarro/PdbSourceIndexing/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MiguelBarro/PdbSourceIndexing'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/MiguelBarro/PdbSourceIndexing/v1.1.0/PdbSourceIndexing/res/Stan.jfif'

        # ReleaseNotes of this module
        ReleaseNotes = '• ExcludePaths
Paths to exclude from source indexing.
This is necessary for private repos where the SRCSVR fails to retrieve the sources due to lack of authorization.

• MappedRepos
Manually mapped repositories provided by the user.
This is necessary if the sourcesare not into a git repository and automatic introspection is not possible.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://raw.githubusercontent.com/MiguelBarro/PdbSourceIndexing/main/README.md'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
