name: Dependency distributable generator
on:
  workflow_dispatch:
  
defaults:
  run:
    shell: pwsh

jobs:
  windows:
    runs-on: windows-2025

    steps:
      - name: Create workspace and build
        run: |
          # Create a workspace for the build
          $install = mkdir install
          mkdir depends | cd
          vcpkg new --application

          # Set up dependencies
          vcpkg add port protobuf
          vcpkg add port librdkafka

          # Create port overlays to use visual studio generator on protobuf and kafka
          git clone --depth 1 --no-checkout --filter=blob:none --sparse https://github.com/MiguelBarro/vcpkg overlay
          git -C overlay sparse-checkout add ports/protobuf
          git -C overlay sparse-checkout add ports/librdkafka
          git -C overlay checkout

          # modify the vcpkg_cmake_configure() call
          Get-ChildItem -Path overlay/* -R -Filter portfile.cmake | % {
            $file = $_
            (Get-Content $file) | % {
              if ($_ -match '^vcpkg_cmake_configure') {
                "set(VCPKG_PLATFORM_TOOLSET v143)", $_, "WINDOWS_USE_MSBUILD"
              } else { $_ }
            } | Set-Content -Path $file -Encoding utf8
          }

          # install
          $overlays = Get-Item overlay/ports
          vcpkg install `
                --x-install-root=$install `
                --overlay-ports=$overlays `
                --triplet=x64-windows-static
                        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-14.44.35207-10.0.26100.0
          path: ./install/

# vim: set cursorcolumn:tabstop=2 shiftwidth=-1 expandtab:
